name: MOVE ISSUE TO TRIAGE
on:
  issues:
    types:
      - opened

jobs:
  move-issues-into-triage:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: inner-support-project
          column: triage
          repo-token: ${{ secrets.INNER_SUPPORT_TOKEN }}
