on:
  issues:
    types:
      - opened

name: SLACK NOTIFY
jobs:
  slack-notify:
    name: NOTIFY
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: NOTIFICATION
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: Post Title
